{
  inputs,
  lib,
  pkgs,
  ...
}:
let
  idleFadeSeconds = 5;
  screenOffTimeout = 5 * 60;
  lockTimeout = 5 * 60 + 10;
  suspendTimeout = 15 * 60;

  sunsetr = inputs.sunsetr.packages.${pkgs.stdenv.hostPlatform.system}.sunsetr;
in
{
  imports = [
    inputs.noctalia.homeModules.default
  ];

  home.packages = [
    pkgs.ddcutil
    sunsetr
  ];

  xdg.configFile."noctalia/templates/swaylock.conf".text = ''
    # Generated by Noctalia from the active wallpaper and palette.
    image={{ image }}
    scaling=fill
    effect-blur=12x3
    effect-vignette=0.30:0.65

    indicator
    indicator-radius=120
    indicator-thickness=20

    inside-color=00000000
    ring-color={{ colors.primary.default.hex_stripped }}
    line-color=00000000
    separator-color=00000000
    text-color={{ colors.primary.default.hex_stripped }}
    key-hl-color={{ colors.on_tertiary.default.hex_stripped }}
    bs-hl-color={{ colors.on_error.default.hex_stripped }}

    inside-ver-color=00000000
    ring-ver-color={{ colors.tertiary.default.hex_stripped }}
    text-ver-color={{ colors.tertiary.default.hex_stripped }}
    line-ver-color=00000000

    inside-wrong-color=00000000
    ring-wrong-color={{ colors.error.default.hex_stripped }}
    text-wrong-color={{ colors.error.default.hex_stripped }}
    line-wrong-color=00000000

    inside-clear-color=00000000
    ring-clear-color={{ colors.outline.default.hex_stripped }}
    text-clear-color={{ colors.outline.default.hex_stripped }}
    line-clear-color=00000000
  '';

  # swayidle used for its events, not idling
  services.swayidle = {
    enable = true;
    events = rec {
      lock = "pidof swaylock || ${lib.getExe pkgs.swaylock-effects} --daemonize";
      before-sleep = lock;
    };
  };

  # `sunsetr set` atomically replaces this file for manual adjustments. Force
  # recreation on activation so Home Manager can restore the declared baseline.
  xdg.configFile."sunsetr/sunsetr.toml" = {
    force = true;
    text = ''
      backend = "wayland"
      transition_mode = "finish_by"
      smoothing = true
      startup_duration = 0.5
      shutdown_duration = 0.5

      day_temp = 6500
      night_temp = 2500
      day_gamma = 100
      night_gamma = 100

      sunset = "22:00:00"
      sunrise = "07:00:00"
      transition_duration = 30
    '';
  };

  # The same preset command toggles this neutral profile back to the default schedule
  xdg.configFile."sunsetr/presets/disabled/sunsetr.toml" = {
    force = true;
    text = ''
      transition_mode = "static"
      static_temp = 6500
      static_gamma = 100
    '';
  };

  systemd.user.services.sunsetr = {
    Unit = {
      Description = "Sunsetr Wayland night light";
      After = [ "graphical-session.target" ];
      PartOf = [ "graphical-session.target" ];
    };
    Service = {
      ExecStart = "${sunsetr}/bin/sunsetr";
      Restart = "on-failure";
      RestartSec = 2;
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  programs.noctalia = {
    enable = true;

    systemd.enable = true;

    settings = {
      audio = {
        enable_sounds = true;
      };

      bar.default = {
        end = [
          "media"
          "nightlight-toggle"
          "wallpaper"
          "notifications"
          "clipboard"
          "network"
          "bluetooth"
          "volume"
          "brightness"
          "battery"
          "session"
        ];
        font_family = "monospace";
        margin_ends = 10;
        margin_edge = 10;
        concave_edge_corners = false;
        scale = 1.1;
        start = [
          "control-center"
          "tray"
          "workspaces"
          "date"
          "privacy"
        ];
        widget_spacing = 10;
      };

      calendar = {
        enabled = true;
        account.primary = {
          name = "Personal";
          provider = "custom";
          type = "caldav";
          server_url = "https://dav.joinemm.dev/joonas/2a465ca7-ebea-45ff-db4d-61eb39cf6631";
          username = "joonas";
        };
      };

      control_center.sidebar = "full";

      desktop_widgets.enabled = false;

      idle = {
        behavior_order = [
          "screen-off"
          "lock"
          "suspend"
        ];
        pre_action_fade_seconds = idleFadeSeconds;

        behavior = {
          screen-off = {
            action = "screen_off";
            enabled = true;
            timeout = screenOffTimeout - idleFadeSeconds;
          };
          lock = {
            # Noctalia's own lockscreen is disabled; start the external locker directly.
            action = "command";
            command = "loginctl lock-session";
            enabled = true;
            timeout = lockTimeout - idleFadeSeconds;
          };
          suspend = {
            # The Swayidle before-sleep hook locks before every suspend route.
            action = "suspend";
            enabled = true;
            timeout = suspendTimeout - idleFadeSeconds;
          };
        };
      };

      location.auto_locate = true;

      lockscreen = {
        enabled = false;
        fingerprint = false;
      };

      shell = {
        clipboard_confirm_clear_history = false;
        screen_time_enabled = true;
        settings_show_advanced = true;
        screen_corners.enabled = true;
        polkit_agent = true;

        panel = {
          clipboard_placement = "attached";
          open_near_click_clipboard = true;
          open_near_click_control_center = true;
          open_near_click_session = true;
          open_near_click_wallpaper = true;
        };

        session.actions = [
          {
            enabled = true;
            action = "logout";
            variant = "default";
            shortcut = "l";
          }
          {
            enabled = true;
            action = "suspend";
            variant = "default";
            shortcut = "s";
          }
          {
            enabled = true;
            action = "command";
            command = "systemctl reboot --firmware-setup";
            glyph = "settings-filled";
            label = "BIOS";
            variant = "secondary";
            shortcut = "b";
          }
          {
            enabled = true;
            action = "reboot";
            variant = "destructive";
            shortcut = "r";
          }
          {
            enabled = true;
            action = "shutdown";
            variant = "destructive";
            label = "Power off";
            shortcut = "p";
          }
        ];
      };

      theme = {
        source = "wallpaper";
        templates = {
          builtin_ids = [
            "foot"
            "niri"
          ];
          community_ids = [ "zen-browser" ];

          user.swaylock = {
            enabled = true;
            input_path = "$XDG_CONFIG_HOME/noctalia/templates/swaylock.conf";
            output_path = "$XDG_CONFIG_HOME/swaylock/config";
          };
        };
      };

      wallpaper.directory = "/home/joonas/pictures/wallpapers";

      widget = {
        nightlight-toggle = {
          type = "custom_button";
          glyph = "moon";
          tooltip = "Toggle night light schedule";
          command = "${sunsetr}/bin/sunsetr preset toggle";
        };
        date.format = "{:%A %d.%m.}";
        control-center.glyph = "layout-filled";
        media = {
          art_size = 20;
          hide_when_no_media = true;
          max_length = 350;
          title_scroll = "on_hover";
        };
        tray.capsule = true;
      };

      osd.kinds.lock_keys = false;

      # disable notification sound on apps that already have sounds built in
      notification.filter = {
        slack = {
          enabled = true;
          match = "slack";
          play_sound = false;
        };
        discord = {
          enabled = true;
          match = "vesktop";
          play_sound = false;
        };
      };
    };
  };
}
