{
  lib,
  pkgs,
  config,
  ...
}:
lib.mkMerge [
  {
    # swayidle used for its events, not idling
    services.swayidle = {
      enable = true;
      events = rec {
        lock = "pidof swaylock || ${lib.getExe pkgs.swaylock-effects} --daemonize";
        before-sleep = lock;
      };
    };
  }
  (lib.mkIf config.programs.noctalia.enable {
    xdg.configFile."noctalia/templates/swaylock.conf".text = ''
      # Generated by Noctalia from the active wallpaper and palette.
      image={{ image }}
      scaling=fill
      effect-blur=12x3
      effect-vignette=0.30:0.65

      indicator
      indicator-radius=120
      indicator-thickness=20

      inside-color=00000000
      ring-color={{ colors.primary.default.hex_stripped }}
      line-color={{ colors.on_tertiary.default.hex_stripped }}
      separator-color=00000000
      text-color={{ colors.primary.default.hex_stripped }}
      key-hl-color={{ colors.on_tertiary.default.hex_stripped }}
      bs-hl-color={{ colors.on_error.default.hex_stripped }}

      inside-ver-color=00000000
      ring-ver-color={{ colors.tertiary.default.hex_stripped }}
      text-ver-color={{ colors.tertiary.default.hex_stripped }}
      line-ver-color={{ colors.on_tertiary.default.hex_stripped }}

      inside-wrong-color=00000000
      ring-wrong-color={{ colors.error.default.hex_stripped }}
      text-wrong-color={{ colors.error.default.hex_stripped }}
      line-wrong-color={{ colors.on_tertiary.default.hex_stripped }}

      inside-clear-color=00000000
      ring-clear-color={{ colors.outline.default.hex_stripped }}
      text-clear-color={{ colors.outline.default.hex_stripped }}
      line-clear-color={{ colors.on_tertiary.default.hex_stripped }}
    '';

    programs.noctalia.settings.theme.templates.user.swaylock = {
      enabled = true;
      input_path = "$XDG_CONFIG_HOME/noctalia/templates/swaylock.conf";
      output_path = "$XDG_CONFIG_HOME/swaylock/config";
    };
  })
]
