name: Nix Build

on:
  push:

permissions:
  contents: read
  id-token: write # Required for nixs3 OIDC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: wimpysworld/nothing-but-nix@v10
        with:
          hatchet-protocol: 'holster'

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            builders = @/etc/nix/machines

      - uses: Mic92/niks3-action@v1
        with:
          server-url: https://niks3.joinemm.dev

      - name: Configure remote builders
        run: |
          sudo sh -c "umask 377; echo '${{ secrets.BUILDER_SSH_KEY }}' >/etc/nix/id_builder_key"

          sudo sh -c "echo 'ssh-ng://jrautiola@builder.vedenemo.dev x86_64-linux,i686-linux /etc/nix/id_builder_key 48 1 kvm,benchmark,big-parallel,nixos-test - -' >/etc/nix/machines"
          sudo sh -c "echo 'builder.vedenemo.dev ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG68NdmOw3mhiBZwDv81dXitePoc1w//p/LpsHHA8QRp' >/etc/ssh/ssh_known_hosts"

      # - uses: webfactory/ssh-agent@v0.10.0
      #   with:
      #     ssh-private-key: 
      #       ${{ secrets.BUILDER_SSH_KEY }}
      #
      # - name: Set up known hosts
      #   run: |
      #     sudo sh -c "echo 'builder.vedenemo.dev ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG68NdmOw3mhiBZwDv81dXitePoc1w//p/LpsHHA8QRp' >>/etc/ssh/ssh_known_hosts"
      #
      - name: nix fast build
        run: |
          nix run github:Mic92/nix-fast-build -- \
            --no-nom \
            --skip-cached --option accept-flake-config true \
            --flake .#ci-targets
