name: Nix Build

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  id-token: write # Required for nixs3 OIDC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: wimpysworld/nothing-but-nix@v10
        with:
          hatchet-protocol: 'holster'

      - uses: canidae-solutions/lix-quick-install-action@v4

      - uses: Mic92/niks3-action@v1
        with:
          server-url: https://niks3.joinemm.dev

      - uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: 
            ${{ secrets.BUILDER_SSH_KEY }}

      - name: Build ${{ matrix.host }}
        run: |
          sudo sh -c "echo 'builder.vedenemo.dev ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG68NdmOw3mhiBZwDv81dXitePoc1w//p/LpsHHA8QRp' >>/etc/ssh/ssh_known_hosts"
          nix run github:Mic92/nix-fast-build -- \
            --remote jrautiola@builder.vedenemo.dev --no-download --no-nom \
            --skip-cached --option accept-flake-config true --niks3-server https://niks3.joinemm.dev \
            --flake .#ci-targets
