name: Nix Flake check

on:
  push:
  pull_request:

permissions:
  contents: read
  id-token: write # Required for nixs3 OIDC

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: wimpysworld/nothing-but-nix@v10
        with:
          hatchet-protocol: 'holster'

      - uses: cachix/install-nix-action@v31
            
      - uses: Mic92/niks3-action@v1
        with:
          server-url: https://niks3.joinemm.dev
          
      - name: Run nix flake check 
        run: nix flake check --accept-flake-config --no-build
